import { describe,expect,it,beforeEach } from 'vitest'
import { createHmac } from 'node:crypto'
import { MemoryRepository } from '../../lib/repositories/memory/memory-repository'
import { MockPaymentProvider } from '../../lib/payments/mock'
import type { BookingContext } from '../../lib/repositories/contracts'
import type { CreateOrderInput,PaymentProvider,ProviderOrder } from '../../lib/payments/provider'
import { approveManualPayment,claimManualPayment,createPaymentAttempt,processCashfreeWebhook,reconcileOrder,rejectManualPayment } from '../../lib/services/payments/payment-service'
import { audit } from '../../lib/services/bookings/booking-engine'
import { cancelBooking } from '../../lib/services/cancellations/cancellation-service'
import { zonedDateTime } from '../../lib/domain/time'

process.env.BOOKING_LOOKUP_HMAC_SECRET='manual-upi-test-secret-that-is-at-least-32-characters'
process.env.CASHFREE_CLIENT_SECRET='manual-upi-webhook-secret'
process.env.PAYMENT_PROVIDER='mock'

const future=(hour=18)=>{const date=new Date(Date.now()+4*86400000).toISOString().slice(0,10);return zonedDateTime(date,hour*60,'Asia/Kolkata')}
const context=(mode:'MANUAL_UPI'|'CASHFREE'='MANUAL_UPI'):BookingContext=>({tenant:{id:'tenant-a',slug:'arena-a',legalName:'Arena Pvt Ltd',displayName:'Arena',status:'ACTIVE',timezone:'Asia/Kolkata',createdAt:'',updatedAt:''},turf:{tenantId:'tenant-a',turfId:'turf-1',slug:'arena-a',name:'Arena',shortName:'Arena',address:'Address',locality:'City',mapUrl:'',phone:'919999999999',whatsapp:'919999999999',sports:['Football'],amenities:[],timezone:'Asia/Kolkata',branding:{},isBookingEnabled:true},settings:{paymentMode:'PERCENTAGE',paymentCollectionMode:mode,manualUpi:{upiId:'arena@upi',payeeName:'Arena Sports',instructions:'Use the reference shown.'},advanceValue:50,minDurationMinutes:60,maxDurationMinutes:180,slotIntervalMinutes:30,cancellationEnabled:true,cancellationCutoffHours:4,bookingWindowDays:365,holdDurationMinutes:10},hours:Array.from({length:7},(_,weekday)=>({weekday,closed:false,openMinute:0,closeMinute:1440})),pricingRules:[{id:'base-v1',tenantId:'tenant-a',turfId:'turf-1',days:[0,1,2,3,4,5,6],startTime:0,endTime:1440,hourlyRate:1200,currency:'INR',priority:1}]})
const input=(hour=18)=>({turfId:'turf-1',startAt:future(hour),durationMinutes:60,customerName:'Player One',customerPhone:'919999999999',customerSessionId:'customer-session-0001',idempotencyKey:crypto.randomUUID()})

describe('repaired hold lifecycle and Manual UPI',()=>{
 let repo:MemoryRepository,provider:MockPaymentProvider
 beforeEach(()=>{repo=new MemoryRepository();provider=new MockPaymentProvider()})

 it('expires ACTIVE holds idempotently, releases only HOLD locks, and preserves PAYMENT_PENDING',async()=>{repo.seed(context());const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1'),order=await repo.getPaymentOrder(created.merchantOrderId),hold=repo.holds.get(order!.holdId)!;repo.holds.set(hold.id,{...hold,expiresAt:new Date(Date.now()-1000).toISOString()});expect(await repo.expireHoldAtomic('tenant-a',hold.id,new Date().toISOString(),audit('tenant-a','SYSTEM','test','HOLD_EXPIRED','HOLD',hold.id,'r2'))).toBe('EXPIRED');expect(repo.locks.size).toBe(0);expect(await repo.expireHoldAtomic('tenant-a',hold.id,new Date().toISOString(),audit('tenant-a','SYSTEM','test','HOLD_EXPIRED','HOLD',hold.id,'r3'))).toBe('SKIPPED');const next=await createPaymentAttempt(repo,provider,'arena-a',input(),'r4'),nextOrder=await repo.getPaymentOrder(next.merchantOrderId);await claimManualPayment(repo,nextOrder!,'customer-session-0001','r5');repo.holds.set(nextOrder!.holdId,{...repo.holds.get(nextOrder!.holdId)!,expiresAt:new Date(Date.now()-1000).toISOString()});expect(await repo.expireHoldAtomic('tenant-a',nextOrder!.holdId,new Date().toISOString(),audit('tenant-a','SYSTEM','test','HOLD_EXPIRED','HOLD',nextOrder!.holdId,'r6'))).toBe('SKIPPED');expect([...repo.locks.values()].some(lock=>lock.resourceId===nextOrder!.holdId)).toBe(true)})

 it('cleanup cannot remove BOOKING or BLOCK locks even when resource ids match',async()=>{repo.seed(context());const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1'),order=await repo.getPaymentOrder(created.merchantOrderId),hold=repo.holds.get(order!.holdId)!;repo.holds.set(hold.id,{...hold,expiresAt:new Date(Date.now()-1000).toISOString()});const locks=[...repo.locks.entries()];repo.locks.set(locks[0][0],{...locks[0][1],lockType:'BOOKING'});repo.locks.set(locks[1][0],{...locks[1][1],lockType:'BLOCK'});await repo.expireHoldAtomic('tenant-a',hold.id,new Date().toISOString(),audit('tenant-a','SYSTEM','test','HOLD_EXPIRED','HOLD',hold.id,'r2'));expect([...repo.locks.values()].map(lock=>lock.lockType).sort()).toEqual(['BLOCK','BOOKING'])})

 it('uses an authoritative amount in the generic UPI URI and owner approval is idempotent',async()=>{const ctx=context();repo.seed(ctx);const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1');expect(created.upiUri).toContain('pa=arena%40upi');expect(created.upiUri).toContain('am=600.00');expect(created).not.toHaveProperty('customer');expect(created).not.toHaveProperty('customerAccessTokenHash');const order=await repo.getPaymentOrder(created.merchantOrderId);const claim=await claimManualPayment(repo,order!,'customer-session-0001','r2');expect(claim.status).toBe('PAYMENT_PENDING');expect(repo.bookings.size).toBe(0);ctx.pricingRules[0].hourlyRate=2000;await expect(approveManualPayment(repo,created.merchantOrderId,'tenant-other','owner-b','r3')).rejects.toMatchObject({code:'BOOKING_NOT_FOUND'});const first=await approveManualPayment(repo,created.merchantOrderId,'tenant-a','owner-a','r4'),second=await approveManualPayment(repo,created.merchantOrderId,'tenant-a','owner-a','r5');expect(first.id).toBe(second.id);expect(first.finalPrice).toBe(1200);expect(first.amountPaid).toBe(600);expect(first.paymentMethod).toBe('MANUAL_UPI');expect(repo.bookings.size).toBe(1);expect([...repo.locks.values()].every(lock=>lock.lockType==='BOOKING')).toBe(true)})

 it('rejects invalid Manual UPI configuration before creating a hold',async()=>{const ctx=context();ctx.settings.manualUpi={upiId:'not-valid'};repo.seed(ctx);await expect(createPaymentAttempt(repo,provider,'arena-a',input(),'r1')).rejects.toMatchObject({code:'CONFIGURATION_ERROR'});expect(repo.holds.size).toBe(0)})

 it('rejects a different customer session and prevents another pending claim for the same session',async()=>{repo.seed(context());const data=input(),created=await createPaymentAttempt(repo,provider,'arena-a',data,'r1'),order=await repo.getPaymentOrder(created.merchantOrderId);await expect(claimManualPayment(repo,order!,'different-customer-session','r2')).rejects.toMatchObject({code:'HOLD_EXPIRED'});await claimManualPayment(repo,order!,data.customerSessionId,'r3');await expect(createPaymentAttempt(repo,provider,'arena-a',{...input(20),customerSessionId:data.customerSessionId},'r4')).rejects.toMatchObject({code:'PAYMENT_PENDING'})})

 it('rejects claims after the deadline and rejection releases the slot idempotently',async()=>{repo.seed(context());const late=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1'),lateOrder=await repo.getPaymentOrder(late.merchantOrderId);repo.holds.set(lateOrder!.holdId,{...repo.holds.get(lateOrder!.holdId)!,expiresAt:new Date(Date.now()-1000).toISOString()});await expect(claimManualPayment(repo,lateOrder!,'customer-session-0001','r2')).rejects.toMatchObject({code:'HOLD_EXPIRED'});await repo.expireHoldAtomic('tenant-a',lateOrder!.holdId,new Date().toISOString(),audit('tenant-a','SYSTEM','test','HOLD_EXPIRED','HOLD',lateOrder!.holdId,'r3'));const nextInput=input(),next=await createPaymentAttempt(repo,provider,'arena-a',nextInput,'r4'),order=await repo.getPaymentOrder(next.merchantOrderId);await claimManualPayment(repo,order!,nextInput.customerSessionId,'r5');const first=await rejectManualPayment(repo,next.merchantOrderId,'tenant-a','owner-a','Not found','r6'),second=await rejectManualPayment(repo,next.merchantOrderId,'tenant-a','owner-a','Not found','r7');expect(first.status).toBe('REJECTED');expect(second.status).toBe('REJECTED');expect([...repo.locks.values()].some(lock=>lock.resourceId===order!.holdId)).toBe(false)})

 it('never sends a Manual UPI cancellation to Cashfree refund handling',async()=>{repo.seed(context());const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1'),order=await repo.getPaymentOrder(created.merchantOrderId);await claimManualPayment(repo,order!,'customer-session-0001','r2');const booking=await approveManualPayment(repo,created.merchantOrderId,'tenant-a','owner-a','r3');const result=await cancelBooking(repo,provider,booking.id,{type:'USER',id:'owner-a'},'Cancelled by owner',crypto.randomUUID(),'tenant-a');expect(result.manualRefundRequired).toBe(true);expect(provider.refunds.size).toBe(0)})

 it('expires an abandoned active Cashfree order at the local deadline and releases its locks',async()=>{repo.seed(context('CASHFREE'));const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1'),order=await repo.getPaymentOrder(created.merchantOrderId),expiredAt=new Date(Date.now()-1000).toISOString();repo.orders.set(created.merchantOrderId,{...order!,expiresAt:expiredAt});repo.holds.set(order!.holdId,{...repo.holds.get(order!.holdId)!,expiresAt:expiredAt});expect(await reconcileOrder(repo,provider,created.merchantOrderId,'r2')).toEqual({status:'EXPIRED',bookingId:undefined});expect((await repo.getPaymentOrder(created.merchantOrderId))?.status).toBe('EXPIRED');expect(repo.holds.get(order!.holdId)?.status).toBe('EXPIRED');expect([...repo.locks.values()].some(lock=>lock.resourceId===order!.holdId)).toBe(false)})

 it('keeps the captured Cashfree price and exposes late paid money for attention',async()=>{const ctx=context('CASHFREE');repo.seed(ctx);const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1'),remote=provider.orders.get(created.merchantOrderId)!;ctx.pricingRules[0].hourlyRate=2000;provider.orders.set(created.merchantOrderId,{...remote,status:'PAID'});const confirmed=await reconcileOrder(repo,provider,created.merchantOrderId,'r2'),booking=repo.bookings.get(confirmed.bookingId!);expect(booking?.finalPrice).toBe(1200);const another=await createPaymentAttempt(repo,provider,'arena-a',input(20),'r3'),anotherOrder=await repo.getPaymentOrder(another.merchantOrderId),anotherRemote=provider.orders.get(another.merchantOrderId)!;repo.holds.set(anotherOrder!.holdId,{...repo.holds.get(anotherOrder!.holdId)!,expiresAt:new Date(Date.now()-1000).toISOString()});await repo.expireHoldAtomic('tenant-a',anotherOrder!.holdId,new Date().toISOString(),audit('tenant-a','SYSTEM','test','HOLD_EXPIRED','HOLD',anotherOrder!.holdId,'r4'));provider.orders.set(another.merchantOrderId,{...anotherRemote,status:'PAID'});await expect(reconcileOrder(repo,provider,another.merchantOrderId,'r5')).rejects.toMatchObject({code:'HOLD_EXPIRED'});expect((await repo.getPaymentOrder(another.merchantOrderId))?.status).toBe('REQUIRES_ATTENTION')})

 it('persists failed Cashfree events instead of leaving the order ACTIVE',async()=>{repo.seed(context('CASHFREE'));const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1'),body=JSON.stringify({type:'PAYMENT_FAILED_WEBHOOK',data:{order:{order_id:created.merchantOrderId,order_amount:created.payableNow,order_currency:'INR'},payment:{payment_status:'FAILED',payment_amount:created.payableNow,payment_currency:'INR'}}}),timestamp=String(Date.now()),signature=createHmac('sha256',process.env.CASHFREE_CLIENT_SECRET!).update(timestamp+body).digest('base64');await processCashfreeWebhook(repo,provider,body,timestamp,signature,'r2');expect((await repo.getPaymentOrder(created.merchantOrderId))?.status).toBe('FAILED')})
})

class FlakyProvider implements PaymentProvider{
 calls=0;order?:ProviderOrder
 async createOrder(input:CreateOrderInput){this.calls++;if(this.calls===1)throw new Error('network');return this.order={providerOrderId:`cf_${input.merchantOrderId}`,paymentSessionId:'session-ok',status:'ACTIVE',amount:input.amount,currency:input.currency,expiresAt:input.expiresAt}}
 async getOrder(){if(!this.order)throw new Error('not found');return this.order}
 async getPaymentsForOrder(){return[]}
 verifyWebhook(){return false}
 async createRefund(){return{providerRefundId:'none',status:'FAILED' as const,amount:0}}
 async getRefund(){return{providerRefundId:'none',status:'FAILED' as const,amount:0}}
}

describe('Cashfree create-order recovery',()=>{it('retries provider creation against the same idempotent merchant order',async()=>{const repo=new MemoryRepository(),provider=new FlakyProvider();repo.seed(context('CASHFREE'));const data=input();await expect(createPaymentAttempt(repo,provider,'arena-a',data,'r1')).rejects.toThrow('network');const recovered=await createPaymentAttempt(repo,provider,'arena-a',data,'r2');expect(recovered.paymentSessionId).toBe('session-ok');expect(provider.calls).toBe(2);expect(repo.orders.size).toBe(1);expect(repo.holds.size).toBe(1)})})
