import { createHmac,randomUUID } from 'node:crypto'
import { beforeEach,describe,expect,it } from 'vitest'
import { MemoryRepository } from '../../lib/repositories/memory/memory-repository'
import { MockPaymentProvider } from '../../lib/payments/mock'
import { createPaymentAttempt,processCashfreeWebhook,reconcileOrder,verifyStoredPaymentToken } from '../../lib/services/payments/payment-service'
import type { BookingContext } from '../../lib/repositories/contracts'
import { zonedDateTime } from '../../lib/domain/time'

process.env.BOOKING_LOOKUP_HMAC_SECRET='payment-test-secret-that-is-at-least-32-characters'
process.env.CASHFREE_CLIENT_SECRET='mock-webhook-secret'
process.env.PAYMENT_PROVIDER='mock'
const future=()=>zonedDateTime(new Date(Date.now()+2*86400000).toISOString().slice(0,10),19*60,'Asia/Kolkata')
const ctx:BookingContext={tenant:{id:'tenant-a',slug:'arena-a',legalName:'Arena',displayName:'Arena',status:'ACTIVE',timezone:'Asia/Kolkata',createdAt:'',updatedAt:''},turf:{tenantId:'tenant-a',turfId:'turf-1',slug:'arena-a',name:'Arena',shortName:'Arena',address:'Address',locality:'City',mapUrl:'',phone:'919999999999',whatsapp:'919999999999',sports:['Football'],amenities:[],timezone:'Asia/Kolkata',branding:{},isBookingEnabled:true},settings:{paymentMode:'PERCENTAGE',advanceValue:50,minDurationMinutes:60,maxDurationMinutes:180,slotIntervalMinutes:30,cancellationEnabled:true,cancellationCutoffHours:4,bookingWindowDays:365,holdDurationMinutes:10},hours:Array.from({length:7},(_,weekday)=>({weekday,closed:false,openMinute:0,closeMinute:1440})),pricingRules:[{id:'base',tenantId:'tenant-a',turfId:'turf-1',days:[0,1,2,3,4,5,6],startTime:0,endTime:1440,hourlyRate:1200,currency:'INR',priority:1}]}
const input=()=>({turfId:'turf-1',startAt:future(),durationMinutes:60,customerName:'Test Customer',customerPhone:'919999999999',customerSessionId:'customer-session-0001',idempotencyKey:randomUUID()})

describe('payment contract',()=>{let repo:MemoryRepository;let provider:MockPaymentProvider;beforeEach(()=>{repo=new MemoryRepository();repo.seed(ctx);provider=new MockPaymentProvider()})
 it('uses server pricing and safely retries the same idempotency key',async()=>{const data=input();const first=await createPaymentAttempt(repo,provider,'arena-a',data,'r1');const second=await createPaymentAttempt(repo,provider,'arena-a',data,'r2');expect(first.payableNow).toBe(600);expect(second.merchantOrderId).toBe(first.merchantOrderId);expect(repo.orders.size).toBe(1);expect(repo.holds.size).toBe(1);const stored=await repo.getPaymentOrder(first.merchantOrderId);expect(await verifyStoredPaymentToken(second.customerStatusToken,stored!)).toBe(true)})
 it('return reconciliation creates one booking only after provider says paid',async()=>{const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1');expect(await reconcileOrder(repo,provider,created.merchantOrderId,'r2')).toEqual({status:'ACTIVE',bookingId:undefined});const remote=provider.orders.get(created.merchantOrderId)!;provider.orders.set(created.merchantOrderId,{...remote,status:'PAID',providerPaymentId:'pay-1'});const one=await reconcileOrder(repo,provider,created.merchantOrderId,'r3');const two=await reconcileOrder(repo,provider,created.merchantOrderId,'r4');expect(one.bookingId).toBeTruthy();expect(two.bookingId).toBe(one.bookingId);expect(repo.bookings.size).toBe(1)})
 it('rejects invalid signatures and mismatched amounts',async()=>{const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1');const body=JSON.stringify({type:'PAYMENT_SUCCESS_WEBHOOK',data:{order:{order_id:created.merchantOrderId,order_amount:1,order_currency:'INR'},payment:{payment_status:'SUCCESS',payment_amount:1,payment_currency:'INR'}}});await expect(processCashfreeWebhook(repo,provider,body,String(Date.now()),'bad','r2')).rejects.toMatchObject({code:'FORBIDDEN'});const ts=String(Date.now());const sig=createHmac('sha256',process.env.CASHFREE_CLIENT_SECRET!).update(ts+body).digest('base64');await expect(processCashfreeWebhook(repo,provider,body,ts,sig,'r3')).rejects.toMatchObject({code:'PAYMENT_MISMATCH'});expect(repo.bookings.size).toBe(0)})
 it('ignores failed events and makes duplicate success harmless',async()=>{const created=await createPaymentAttempt(repo,provider,'arena-a',input(),'r1');const send=async(type:string)=>{const body=JSON.stringify({type,data:{order:{order_id:created.merchantOrderId,order_amount:600,order_currency:'INR'},payment:{cf_payment_id:'pay-1',payment_status:type==='PAYMENT_SUCCESS_WEBHOOK'?'SUCCESS':'FAILED',payment_amount:600,payment_currency:'INR'}}});const ts=String(Date.now());const sig=createHmac('sha256',process.env.CASHFREE_CLIENT_SECRET!).update(ts+body).digest('base64');return processCashfreeWebhook(repo,provider,body,ts,sig,'r2')};expect((await send('PAYMENT_FAILED_WEBHOOK')).finalized).toBe(false);await send('PAYMENT_SUCCESS_WEBHOOK');await send('PAYMENT_SUCCESS_WEBHOOK');expect(repo.bookings.size).toBe(1)})
})
