'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { CalendarDays, ChevronRight, House, Plus, Search, Settings2, X } from 'lucide-react'
import type { ReactNode } from 'react'
import { useTurfStore } from '@/stores/turfmate-store'
export const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`
export function Logo({compact=false}:{compact?:boolean}){return <div className="flex items-center gap-2.5"><span className="relative grid size-9 place-items-center overflow-hidden rounded-xl bg-primary text-accent"><span className="absolute inset-x-1 top-1/2 border-t border-accent/50"/><span className="absolute inset-y-1 left-1/2 border-l border-accent/50"/><svg viewBox="0 0 24 24" className="relative size-5"><path d="m5 12 4 4 9-9" fill="none" stroke="currentColor" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round"/></svg></span>{!compact&&<span className="text-[19px] font-extrabold tracking-[-.055em] text-primary">turfmate</span>}</div>}
export function StoreGate({children}:{children:ReactNode}){const state=useTurfStore();if(!state.hydrated)return <main className="mx-auto min-h-dvh max-w-[460px] bg-background p-5"><div className="skeleton h-10 w-36 rounded-xl"/><div className="skeleton mt-10 h-48 rounded-[28px]"/><div className="skeleton mt-7 h-7 w-40 rounded-lg"/><div className="mt-4 grid grid-cols-3 gap-2">{[1,2,3,4,5,6].map(x=><div key={x} className="skeleton h-12 rounded-xl"/>)}</div></main>;return <>{children}</>}
export function Button({variant='primary',className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'accent'|'ghost'|'danger'}){const styles={primary:'bg-primary text-primary-foreground',secondary:'border bg-card text-foreground',accent:'bg-accent text-primary',ghost:'text-primary',danger:'border border-destructive/30 bg-card text-destructive'};return <button {...props} className={`min-h-12 rounded-[14px] px-4 font-semibold transition active:scale-[.99] disabled:active:scale-100 ${styles[variant]} ${className}`}/>} 
export function Field({label,error,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;error?:string}){return <label className="block text-sm font-semibold">{label}<input {...props} aria-invalid={!!error} aria-describedby={error?`${props.name}-error`:undefined} className="mt-2"/>{error&&<span id={`${props.name}-error`} className="mt-1.5 block text-xs text-destructive">{error}</span>}</label>}
export function SelectField({label,children,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string;children:ReactNode}){return <label className="block text-sm font-semibold">{label}<select {...props} className="mt-2">{children}</select></label>}
export function EmptyState({icon='○',title,detail,action}:{icon?:string;title:string;detail:string;action?:ReactNode}){return <div className="rounded-[24px] border bg-card px-6 py-10 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-muted text-xl text-primary">{icon}</span><h2 className="mt-4 text-lg font-bold">{title}</h2><p className="mx-auto mt-2 max-w-xs text-sm leading-6 text-muted-foreground">{detail}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function Badge({children,tone='green'}:{children:ReactNode;tone?:'green'|'amber'|'red'|'grey'}){const c={green:'bg-[#e2efdf] text-[#245235]',amber:'bg-[#fff0c7] text-[#805d13]',red:'bg-[#fbe2df] text-[#91372f]',grey:'bg-muted text-muted-foreground'};return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${c[tone]}`}>{children}</span>}
export function Header({title,subtitle,back}:{title?:string;subtitle?:string;back?:string}){return <header className="sticky top-0 z-20 flex min-h-[72px] items-center gap-3 border-b bg-background/95 px-5 py-3 backdrop-blur">{back?<Link href={back} className="grid size-11 place-items-center rounded-full border bg-card" aria-label="Back">←</Link>:<Logo compact/>}<div className="min-w-0"><p className="truncate font-bold">{title}</p>{subtitle&&<p className="truncate text-xs text-muted-foreground">{subtitle}</p>}</div>{!back&&<div className="ml-auto"><Logo/></div>}</header>}
export function Shell({children,nav,slug}:{children:ReactNode;nav?:'customer'|'owner';slug?:string}){return <main className={`mx-auto min-h-dvh w-full max-w-[460px] overflow-x-clip bg-background shadow-[0_0_45px_rgba(22,53,42,.08)] ${nav?'pb-24':''}`}>{children}{nav&&<BottomNav kind={nav} slug={slug}/>}</main>}
function BottomNav({kind,slug}:{kind:'customer'|'owner';slug?:string}){const path=usePathname();const customer=[[`/t/${slug}`,'Book',House],[`/t/${slug}/booked`,'Booked',Search]] as const;const owner=[['/owner/dashboard','Home',House],['/owner/bookings','Bookings',Search],['/owner/bookings/new','Add',Plus],['/owner/calendar','Calendar',CalendarDays],['/owner/more','More',Settings2]] as const;const links=kind==='owner'?owner:customer;return <nav className="safe-bottom fixed inset-x-0 bottom-0 z-30 mx-auto flex w-full max-w-[460px] justify-around border-t bg-card/96 px-1 pt-2 backdrop-blur">{links.map(([href,label,Icon])=>{const active=href==='/owner/dashboard'?path===href:path===href||path.startsWith(`${href}/`);return <Link key={href} href={href} className={`relative flex min-h-14 min-w-16 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-bold ${active?'text-primary':'text-muted-foreground'}`}><Icon size={label==='Add'?23:19} className={label==='Add'?'rounded-full bg-accent p-1 text-primary':''}/>{label}</Link>})}</nav>}
export function PageTitle({eyebrow,title,detail,action}:{eyebrow?:string;title:string;detail?:string;action?:ReactNode}){return <div className="flex items-end justify-between gap-4"><div>{eyebrow&&<p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#4f715f]">{eyebrow}</p>}<h1 className="mt-1 text-[30px] font-extrabold tracking-[-.045em]">{title}</h1>{detail&&<p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p>}</div>{action}</div>}
export function RowLink({href,title,detail}:{href:string;title:string;detail?:string}){return <Link href={href} className="flex min-h-16 items-center rounded-2xl border bg-card px-4 py-3"><span><strong className="block text-sm">{title}</strong>{detail&&<span className="mt-1 block text-xs text-muted-foreground">{detail}</span>}</span><ChevronRight className="ml-auto text-muted-foreground" size={18}/></Link>}
export function Dialog({title,detail,confirm,cancel,danger=false}:{title:string;detail:string;confirm:()=>void;cancel:()=>void;danger?:boolean}){return <div className="fixed inset-0 z-50 grid place-items-center bg-[#10281f]/55 p-5" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="w-full max-w-sm rounded-[24px] bg-card p-5 shadow-2xl"><div className="flex items-start justify-between"><h2 id="dialog-title" className="text-xl font-bold">{title}</h2><button onClick={cancel} className="grid size-10 place-items-center" aria-label="Close"><X size={19}/></button></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{detail}</p><div className="mt-6 grid grid-cols-2 gap-2"><Button variant="secondary" onClick={cancel}>Keep</Button><Button variant={danger?'danger':'primary'} onClick={confirm}>Confirm</Button></div></div></div>}
export function Toast({children}:{children:ReactNode}){return <div className="fixed inset-x-4 bottom-24 z-50 mx-auto max-w-[420px] rounded-xl bg-[#162d25] px-4 py-3 text-sm text-white shadow-xl" role="status" aria-live="polite">{children}</div>}
