import { createHmac,randomUUID } from 'node:crypto'
import { expect,test,type APIRequestContext,type Page } from '@playwright/test'
import { getApps,initializeApp } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'
import { localDate } from '../../lib/domain/time'

test.describe.configure({mode:'serial'})
const future=(days:number)=>{const date=new Date(`${new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
const at=(days:number,hour:number,minute=0)=>`${future(days)}T${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}:00+05:30`
const owner={email:'owner-a@example.com',password:'Password123!'}
const manualOwner={email:'owner-c@example.com',password:'Password123!'}
const origin='http://127.0.0.1:3100'
let loginSequence=1
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080'
const emulatorDb=()=>getFirestore(getApps().find(app=>app.name==='playwright-e2e')??initializeApp({projectId:'turfmate-e2e'},'playwright-e2e'))

async function login(page:Page,credentials=owner){await page.setExtraHTTPHeaders({'x-forwarded-for':`198.51.100.${loginSequence++}`});await page.goto('/owner/login');await page.getByLabel('Email').fill(credentials.email);await page.getByLabel('Password').fill(credentials.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/owner\/dashboard/)}
async function json<T>(response:Awaited<ReturnType<APIRequestContext['get']>>){const body=await response.json();return body.data as T}
async function manual(request:APIRequestContext,days:number,hour:number,name='E2E Player',durationMinutes=60){return request.post('/api/owner/bookings',{data:{turfId:'main',startAt:at(days,hour),durationMinutes,customerName:name,customerPhone:'9999999999',paymentStatus:'PAY_AT_VENUE'},headers:{origin}})}
async function createOrder(request:APIRequestContext,days:number,hour:number){const response=await request.post('/api/public/tenants/arena-11/payment-orders',{data:{turfId:'main',startAt:at(days,hour),durationMinutes:60,customerName:'Online Player',customerPhone:'9999999999',customerSessionId:`session-${randomUUID()}`,idempotencyKey:randomUUID()}});expect(response.status()).toBe(201);return json<{merchantOrderId:string;payableNow:number;customerStatusToken:string}>(response)}
async function payOrder(request:APIRequestContext,order:{merchantOrderId:string;payableNow:number;customerStatusToken:string},duplicate=false){const body=JSON.stringify({type:'PAYMENT_SUCCESS_WEBHOOK',data:{order:{order_id:order.merchantOrderId,order_amount:order.payableNow,order_currency:'INR'},payment:{cf_payment_id:`pay-${randomUUID()}`,payment_status:'SUCCESS',payment_amount:order.payableNow,payment_currency:'INR'}}}),timestamp=String(Date.now()),signature=createHmac('sha256','e2e-cashfree-secret').update(timestamp+body).digest('base64'),send=()=>request.post('/api/webhooks/cashfree',{data:body,headers:{'content-type':'application/json','x-webhook-timestamp':timestamp,'x-webhook-signature':signature}});const first=await send();expect(first.ok()).toBeTruthy();if(duplicate)expect((await send()).ok()).toBeTruthy();const status=await request.get(`/api/public/payments/${order.merchantOrderId}/status`,{headers:{authorization:`Bearer ${order.customerStatusToken}`}});return json<{status:string;bookingId:string}>(status)}
type ManualOrder={merchantOrderId:string;payableNow:number;customerStatusToken:string;paymentCollectionMode:string;upiUri:string;status:string}
async function createManualOrder(request:APIRequestContext,days:number,hour:number,name:string,customerSessionId=`session-${randomUUID()}`){const response=await request.post('/api/public/tenants/arena-upi/payment-orders',{data:{turfId:'main',startAt:at(days,hour),durationMinutes:60,customerName:name,customerPhone:'9999999999',customerSessionId,idempotencyKey:randomUUID()}});expect(response.status(),await response.text()).toBe(201);return{order:await json<ManualOrder>(response),customerSessionId}}
async function claimManualOrder(request:APIRequestContext,value:{order:ManualOrder;customerSessionId:string}){const response=await request.post(`/api/public/payments/${value.order.merchantOrderId}/claim`,{data:{customerSessionId:value.customerSessionId},headers:{authorization:`Bearer ${value.order.customerStatusToken}`,origin}});expect(response.ok(),await response.text()).toBeTruthy();return json<{status:string}>(response)}
async function openManualPayment(page:Page,days:number,hour:number,name:string){await page.goto('/t/arena-upi');await page.getByLabel('Choose another date').fill(future(days));const start=page.getByRole('button',{name:new RegExp(`^${hour % 12 || 12}:00`)}).first();await expect(start).toBeVisible();await start.click();await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page).toHaveURL(/\/details$/);await page.getByLabel('Full name').fill(name);await page.getByLabel('Mobile number (+91)').fill('9999999999');await page.getByRole('button',{name:'Continue to payment',exact:true}).click();await expect(page).toHaveURL(/\/payment$/);await page.getByRole('button',{name:'Continue to payment',exact:true}).click();await expect(page.getByRole('heading',{name:'Review & pay'})).toBeVisible();await expect(page.getByText('arena11@upi',{exact:true})).toBeVisible();return page.evaluate(()=>{const key=Object.keys(sessionStorage).find(item=>item.startsWith('turfmate:firebase:payment:'));if(!key)throw new Error('Payment token was not persisted.');return{merchantOrderId:key.replace('turfmate:firebase:payment:',''),customerStatusToken:sessionStorage.getItem(key)!}})}
async function firestoreDocument(path:string){const snapshot=await emulatorDb().doc(path).get();expect(snapshot.exists).toBe(true);return snapshot.data()!}
async function patchFirestoreString(path:string,field:string,value:string){await emulatorDb().doc(path).update({[field]:value})}

test('1. owner authentication',async({page})=>{await login(page);await expect(page.getByText('Owner Console').first()).toBeVisible()})

test('2. tenant isolation',async({browser})=>{const b=await browser.newPage();await login(b,{email:'owner-b@example.com',password:'Password123!'});const created=await manual(b.request,35,9,'Tenant B');expect(created.status(),await created.text()).toBe(201);const booking=await json<{id:string}>(created);await b.context().close();const a=await browser.newPage();await login(a);const denied=await a.request.get(`/api/owner/bookings/${booking.id}`);expect(denied.status()).toBe(404);await a.context().close()})

test('3. public tenant resolution',async({request})=>{const response=await request.get('/api/public/tenants/arena-11');expect(response.ok()).toBeTruthy();expect((await json<{tenantId:string;slug:string}>(response))).toMatchObject({tenantId:'tenant-a',slug:'arena-11'})})

test('4. normal customer booking',async({request})=>{const status=await payOrder(request,await createOrder(request,36,10));expect(status.status).toBe('PAID');expect(status.bookingId).toBeTruthy()})

test('5. cross-midnight booking',async({page})=>{await login(page);const response=await manual(page.request,37,23,'Night Player',120);expect(response.status()).toBe(201);const booking=await json<{startAt:string;endAt:string}>(response);expect(localDate(booking.endAt,'Asia/Kolkata')).not.toBe(localDate(booking.startAt,'Asia/Kolkata'))})

test('6. simultaneous booking conflict',async({page})=>{await login(page);const responses=await Promise.all([manual(page.request,38,11,'Conflict One'),manual(page.request,38,11,'Conflict Two')]);expect(responses.map(item=>item.status()).sort()).toEqual([201,409])})

test('7. payment success',async({request})=>{const status=await payOrder(request,await createOrder(request,39,12));expect(status).toMatchObject({status:'PAID'})})

test('8. payment failure remains unconfirmed',async({request})=>{const order=await createOrder(request,40,13),response=await request.get(`/api/public/payments/${order.merchantOrderId}/status`,{headers:{authorization:`Bearer ${order.customerStatusToken}`}}),status=await json<{status:string;bookingId?:string}>(response);expect(status.status).toBe('ACTIVE');expect(status.bookingId).toBeUndefined()})

test('9. duplicate webhook is idempotent',async({request})=>{const status=await payOrder(request,await createOrder(request,41,14),true);expect(status.status).toBe('PAID')})

test('10. manual owner booking',async({page})=>{await login(page);const response=await manual(page.request,42,15,'Manual Owner');expect(response.status()).toBe(201);expect((await json<{source:string}>(response)).source).toBe('MANUAL')})

test('11. block creation and removal',async({page})=>{await login(page);const created=await page.request.post('/api/owner/blocks',{data:{turfId:'main',startAt:at(43,16),endAt:at(43,17),reason:'Maintenance'},headers:{origin}});expect(created.status()).toBe(201);const block=await json<{id:string}>(created),removed=await page.request.delete(`/api/owner/blocks/${block.id}`,{headers:{origin}});expect(removed.ok()).toBeTruthy()})

test('12. pricing change',async({page})=>{await login(page);const rules=await json<Array<{id:string;days:number[];startTime:number;endTime:number}>>(await page.request.get('/api/owner/pricing')),base=rules.find(item=>item.id==='base')!;const response=await page.request.patch('/api/owner/pricing/base',{data:{turfId:'main',days:base.days,startTime:base.startTime,endTime:base.endTime,hourlyRate:1350,currency:'INR',priority:1},headers:{origin}});expect(response.ok()).toBeTruthy()})

test('13. existing pricing snapshot remains unchanged',async({page})=>{await login(page);const created=await manual(page.request,44,10,'Snapshot Player'),booking=await json<{id:string;finalPrice:number}>(created);const rules=await json<Array<{id:string;days:number[];startTime:number;endTime:number}>>(await page.request.get('/api/owner/pricing')),base=rules.find(item=>item.id==='base')!;await page.request.patch('/api/owner/pricing/base',{data:{turfId:'main',days:base.days,startTime:base.startTime,endTime:base.endTime,hourlyRate:1500,currency:'INR',priority:1},headers:{origin}});const existing=await json<{finalPrice:number}>(await page.request.get(`/api/owner/bookings/${booking.id}`));expect(existing.finalPrice).toBe(booking.finalPrice)})

test('14. operating-hours change',async({page})=>{await login(page);const days=await json<Array<{weekday:number;closed:boolean;openMinute:number;closeMinute:number}>>(await page.request.get('/api/owner/operating-hours'));const response=await page.request.patch('/api/owner/operating-hours',{data:{days:days.map(day=>day.weekday===0?{...day,openMinute:60}:day)},headers:{origin}});expect(response.ok()).toBeTruthy()})

test('15. booking lookup',async({page})=>{await login(page);const booking=await json<{id:string}>(await manual(page.request,45,11,'Lookup Player'));const response=await page.request.post('/api/public/bookings/lookup',{data:{bookingId:booking.id,phone:'9999999999'}});expect(response.ok()).toBeTruthy();expect((await json<{accessToken:string}>(response)).accessToken).toBeTruthy()})

test('16. customer cancellation',async({page})=>{await login(page);const booking=await json<{id:string}>(await manual(page.request,46,12,'Cancel Player'));const lookup=await json<{accessToken:string}>(await page.request.post('/api/public/bookings/lookup',{data:{bookingId:booking.id,phone:'9999999999'}}));const response=await page.request.post(`/api/public/bookings/${booking.id}/cancel`,{data:{reason:'Plans changed',idempotencyKey:randomUUID()},headers:{authorization:`Bearer ${lookup.accessToken}`,origin}});expect((await json<{status:string}>(response)).status).toBe('CANCELLED')})

test('17. refund pending',async({request})=>{const paid=await payOrder(request,await createOrder(request,47,13)),lookup=await json<{accessToken:string}>(await request.post('/api/public/bookings/lookup',{data:{bookingId:paid.bookingId,phone:'9999999999'}})),cancel=await request.post(`/api/public/bookings/${paid.bookingId}/cancel`,{data:{reason:'Plans changed',idempotencyKey:randomUUID()},headers:{authorization:`Bearer ${lookup.accessToken}`,origin}});expect((await json<{refundStatus:string}>(cancel)).refundStatus).toBe('PENDING')})

test('18. refund success',async({request})=>{const order=await createOrder(request,48,14),paid=await payOrder(request,order),lookup=await json<{accessToken:string}>(await request.post('/api/public/bookings/lookup',{data:{bookingId:paid.bookingId,phone:'9999999999'}})),cancelled=await json<{refundId:string}>(await request.post(`/api/public/bookings/${paid.bookingId}/cancel`,{data:{reason:'Plans changed',idempotencyKey:randomUUID()},headers:{authorization:`Bearer ${lookup.accessToken}`,origin}})),body=JSON.stringify({type:'REFUND_STATUS_WEBHOOK',data:{refund:{refund_id:cancelled.refundId,cf_refund_id:'cf-e2e-refund',refund_amount:order.payableNow,refund_currency:'INR',refund_status:'SUCCESS'}}}),timestamp=String(Date.now()),signature=createHmac('sha256','e2e-cashfree-secret').update(timestamp+body).digest('base64');const webhook=await request.post('/api/webhooks/cashfree-refunds',{data:body,headers:{'content-type':'application/json','x-webhook-timestamp':timestamp,'x-webhook-signature':signature,'x-idempotency-key':randomUUID()}});expect(webhook.ok()).toBeTruthy();const detail=await json<{paymentStatus:string}>(await request.get(`/api/public/bookings/${paid.bookingId}`,{headers:{authorization:`Bearer ${lookup.accessToken}`}}));expect(detail.paymentStatus).toBe('REFUNDED')})

test('19. owner realtime update',async({page})=>{await login(page);await page.goto('/owner/dashboard');const created=await manual(page.request,0,22,'Realtime Player');expect(created.status(),await created.text()).toBe(201);await expect(page.getByText('Realtime Player')).toBeVisible({timeout:20_000})})

test('20. refresh persistence',async({page})=>{await login(page);await page.reload();await expect(page).toHaveURL(/\/owner\/dashboard/);await expect(page.getByText('Owner Console').first()).toBeVisible()})

test('21. Manual UPI browser claim survives refresh and confirms after realtime owner approval',async({browser})=>{
 test.slow()
 const ownerPage=await browser.newPage();await login(ownerPage,manualOwner);await ownerPage.goto('/owner/dashboard')
 const customer=await browser.newPage();await customer.setViewportSize({width:390,height:844})
 const name='UPI Browser Approval',payment=await openManualPayment(customer,20,10,name)
 await expect(customer.getByRole('link',{name:'Pay via UPI'})).toHaveAttribute('href',/^upi:\/\/pay\?/)
 expect(await customer.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)
 await customer.getByRole('button',{name:"I've Paid",exact:true}).click()
 await expect(customer.getByText('PAYMENT SUBMITTED',{exact:true})).toBeVisible()
 await expect(customer.getByRole('link',{name:'Send Screenshot on WhatsApp'})).toHaveAttribute('href',/^https:\/\/wa\.me\//)
 const claimCard=ownerPage.getByText(name,{exact:true}).locator('xpath=ancestor::div[.//button[normalize-space()="Approve"]][1]')
 await expect(claimCard).toBeVisible()
 await customer.reload();await customer.getByRole('button',{name:'Continue to payment',exact:true}).click()
 await expect(customer.getByText('PAYMENT SUBMITTED',{exact:true})).toBeVisible()
 const refreshedToken=await customer.evaluate(orderId=>sessionStorage.getItem(`turfmate:firebase:payment:${orderId}`),payment.merchantOrderId)
 expect(refreshedToken).toBeTruthy()
 await claimCard.getByRole('button',{name:'Approve',exact:true}).click()
 await expect(claimCard).toHaveCount(0)
 await expect(customer).toHaveURL(new RegExp('/t/arena-upi/success/'),{timeout:20_000});await expect(customer.getByText('You’re playing.')).toBeVisible()
 const status=await customer.request.get(`/api/public/payments/${payment.merchantOrderId}/status`,{headers:{authorization:`Bearer ${refreshedToken}`}})
 expect((await json<{status:string;bookingId?:string}>(status)).bookingId).toBeTruthy()
 await ownerPage.close();await customer.close()
})

test('22. Manual UPI cross-tenant approval is denied and owner rejection releases the slot',async({browser,request})=>{const value=await createManualOrder(request,21,11,'UPI Browser Rejection');expect((await claimManualOrder(request,value)).status).toBe('PAYMENT_PENDING');const wrongOwner=await browser.newPage();await login(wrongOwner);const denied=await wrongOwner.request.post(`/api/owner/payment-claims/${value.order.merchantOrderId}/approve`,{headers:{origin}});expect(denied.status()).toBe(404);await wrongOwner.close();const ownerPage=await browser.newPage();await login(ownerPage,manualOwner);await ownerPage.goto('/owner/dashboard');const claimCard=ownerPage.getByText('UPI Browser Rejection',{exact:true}).locator('xpath=ancestor::div[.//button[normalize-space()="Reject"]][1]');await expect(claimCard).toBeVisible();await claimCard.getByRole('button',{name:'Reject',exact:true}).click();await expect(claimCard).toHaveCount(0);const statusResponse=await request.get(`/api/public/payments/${value.order.merchantOrderId}/status`,{headers:{authorization:`Bearer ${value.order.customerStatusToken}`}}),status=await json<{status:string;bookingId?:string}>(statusResponse);expect(status).toMatchObject({status:'REJECTED'});expect(status.bookingId).toBeUndefined();const replacement=await createManualOrder(request,21,11,'Replacement Player');expect(replacement.order.status).toBe('ACTIVE');await ownerPage.close()})

test('23. confirmed Manual UPI cancellation requires owner-handled refund',async({browser,request})=>{const value=await createManualOrder(request,22,12,'Manual Refund Player');await claimManualOrder(request,value);const ownerPage=await browser.newPage();await login(ownerPage,manualOwner);const approved=await ownerPage.request.post(`/api/owner/payment-claims/${value.order.merchantOrderId}/approve`,{headers:{origin}});expect(approved.ok(),await approved.text()).toBeTruthy();const booking=await json<{id:string}>(approved),lookup=await json<{accessToken:string}>(await request.post('/api/public/bookings/lookup',{data:{bookingId:booking.id,phone:'9999999999'}})),cancel=await request.post(`/api/public/bookings/${booking.id}/cancel`,{data:{reason:'Plans changed',idempotencyKey:randomUUID()},headers:{authorization:`Bearer ${lookup.accessToken}`,origin}}),result=await json<{status:string;manualRefundRequired?:boolean;refundId?:string}>(cancel);expect(result).toMatchObject({status:'CANCELLED',manualRefundRequired:true});expect(result.refundId).toBeUndefined();const detail=await json<{manualRefundRequired?:boolean}>(await request.get(`/api/public/bookings/${booking.id}`,{headers:{authorization:`Bearer ${lookup.accessToken}`}}));expect(detail.manualRefundRequired).toBe(true);const customerPage=await browser.newPage();await customerPage.goto('/t/arena-upi');await customerPage.evaluate(({id,token})=>sessionStorage.setItem(`turfmate:firebase:booking:${id}`,token),{id:booking.id,token:lookup.accessToken});await customerPage.goto(`/t/arena-upi/booking/${booking.id}`);await expect(customerPage.getByText(/direct UPI refund requires manual action/i)).toBeVisible();await ownerPage.goto(`/owner/bookings/${booking.id}`);await expect(ownerPage.getByText(/Direct UPI refund requires manual owner action/)).toBeVisible();await customerPage.close();await ownerPage.close()})

test('24. Cashfree verified browser return reaches confirmation while unpaid return does not',async({page,request})=>{
 const storeReturnState=async(order:{merchantOrderId:string;customerStatusToken:string},startAt:string)=>{await page.goto('/t/arena-11');await page.evaluate(({order,draft})=>{sessionStorage.setItem(`turfmate:firebase:payment:${order.merchantOrderId}`,order.customerStatusToken);sessionStorage.setItem('turfmate:firebase:draft:arena-11',JSON.stringify(draft))},{order,draft:{phone:'9999999999',customerName:'Online Player',startAt,durationMinutes:60,calculatedPrice:1200}})}
 const paidOrder=await createOrder(request,23,13),paid=await payOrder(request,paidOrder)
 await storeReturnState(paidOrder,at(23,13));await page.goto(`/t/arena-11/payment?order_id=${paidOrder.merchantOrderId}`)
 await expect(page).toHaveURL(new RegExp(`/t/arena-11/success/${paid.bookingId}`));await expect(page.getByText('You’re playing.')).toBeVisible()
 const unpaid=await createOrder(request,24,14)
 await storeReturnState(unpaid,at(24,14));await page.goto(`/t/arena-11/payment?order_id=${unpaid.merchantOrderId}`)
 await expect(page.getByRole('alert').filter({hasText:'Payment is still being verified'})).toBeVisible();await expect(page.getByText('You’re playing.')).toHaveCount(0)
})

test('25. Cashfree failed webhook is persisted without creating a booking',async({request})=>{const order=await createOrder(request,25,15),body=JSON.stringify({type:'PAYMENT_FAILED_WEBHOOK',data:{order:{order_id:order.merchantOrderId,order_amount:order.payableNow,order_currency:'INR'},payment:{cf_payment_id:`pay-${randomUUID()}`,payment_status:'FAILED',payment_amount:order.payableNow,payment_currency:'INR'}}}),timestamp=String(Date.now()),signature=createHmac('sha256','e2e-cashfree-secret').update(timestamp+body).digest('base64'),webhook=await request.post('/api/webhooks/cashfree',{data:body,headers:{'content-type':'application/json','x-webhook-timestamp':timestamp,'x-webhook-signature':signature}});expect(webhook.ok(),await webhook.text()).toBeTruthy();expect(await json<{status:string;finalized:boolean}>(webhook)).toMatchObject({status:'FAILED',finalized:false});const stored=await firestoreDocument(`paymentOrders/${order.merchantOrderId}`);expect(stored.status).toBe('FAILED');expect(stored.bookingId).toBeUndefined()})

test('26. scheduled expiration releases an abandoned hold and makes the slot reusable',async({request})=>{const order=await createOrder(request,26,16),stored=await firestoreDocument(`paymentOrders/${order.merchantOrderId}`),holdId=stored.holdId as string;expect(holdId).toBeTruthy();const expiredAt=new Date(Date.now()-60_000).toISOString();await patchFirestoreString(`paymentOrders/${order.merchantOrderId}`,'expiresAt',expiredAt);await patchFirestoreString(`tenants/tenant-a/holds/${holdId}`,'expiresAt',expiredAt);const cleanup=await request.post('/api/internal/expire-holds',{headers:{authorization:'Bearer e2e-cron-secret-that-is-longer-than-32-characters'}});expect(cleanup.ok(),await cleanup.text()).toBeTruthy();const cleanupResult=await json<{results:Array<{tenantId:string;holdId:string;status:string}>}>(cleanup);expect(cleanupResult.results).toContainEqual({tenantId:'tenant-a',holdId,status:'EXPIRED'});const status=await json<{status:string}>(await request.get(`/api/public/payments/${order.merchantOrderId}/status`,{headers:{authorization:`Bearer ${order.customerStatusToken}`}}));expect(status.status).toBe('EXPIRED');const replacement=await createOrder(request,26,16);expect(replacement.merchantOrderId).not.toBe(order.merchantOrderId)})

test('27. rate-limited request',async({request})=>{let last;for(let index=0;index<61;index++)last=await request.get('/api/public/tenants/arena-11',{headers:{'x-forwarded-for':'203.0.113.77'}});expect(last!.status()).toBe(429);expect(last!.headers()['retry-after']).toBeTruthy()})

test('28. invalid App Check',async({request})=>{const response=await request.get('/api/public/tenants/arena-11',{headers:{'x-turfmate-test-app-check-mode':'enforce','x-forwarded-for':'203.0.113.88'}});expect(response.status()).toBe(401);expect((await response.json()).error.code).toBe('INVALID_APP_CHECK')})

test('29. Firebase error state',async({page})=>{await page.goto('/t/not-a-real-turf');await expect(page.getByText('Turf unavailable')).toBeVisible()})

test('30. no Firebase-to-local fallback',async({page})=>{await page.goto('/t/not-a-real-turf');await expect(page.getByText('Fill demo booking')).toHaveCount(0);await expect(page.getByText('Turf unavailable')).toBeVisible()})

test('31. mobile navigation and overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/t/arena-11');await expect(page.getByRole('link',{name:'Book',exact:true})).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow).toBe(false)})
