import { createHash,createHmac } from 'node:crypto'
import { DomainError } from '../../domain/errors'
import type { AuditEvent,PaymentOrder,PriceSegment,ServerBooking,ServerHold,SlotLock } from '../../domain/backend-types'
import type { AuthoritativeRepository,BookingContext } from '../../repositories/contracts'
import { addMinutes,localDate,localMinute,weekday,zonedDateTime } from '../../domain/time'

export const slotLockId=(tenantId:string,turfId:string,startAt:string)=>createHash('sha256').update(`${tenantId}|${turfId}|${startAt}`).digest('hex')
export function lockRange(tenantId:string,turfId:string,startAt:string,endAt:string,interval:number,lockType:'HOLD'|'BOOKING'|'BLOCK',resourceId:string,expiresAt?:string){const locks:SlotLock[]=[];for(let cursor=startAt;new Date(cursor)<new Date(endAt);cursor=addMinutes(cursor,interval)){const next=addMinutes(cursor,interval);locks.push({id:slotLockId(tenantId,turfId,cursor),tenantId,turfId,slotStartAt:cursor,slotEndAt:next,lockType,resourceId,expiresAt,reconciled:false,createdAt:new Date().toISOString()})}return locks}
export function assertBookable(context:BookingContext,startAt:string,durationMinutes:number){const {settings,turf,hours}=context;if(durationMinutes<settings.minDurationMinutes||durationMinutes>settings.maxDurationMinutes||durationMinutes%settings.slotIntervalMinutes!==0)throw new DomainError('INVALID_TIME_RANGE','Choose a valid booking duration.',400);const endAt=addMinutes(startAt,durationMinutes);const date=localDate(startAt,turf.timezone);const day=hours.find(h=>h.weekday===weekday(date));if(!day||day.closed)throw new DomainError('OUTSIDE_OPERATING_HOURS','The turf is closed on this day.',409);const open=zonedDateTime(date,day.openMinute,turf.timezone);const close=zonedDateTime(date,day.closeMinute,turf.timezone);if(new Date(startAt)<new Date(open)||new Date(endAt)>new Date(close))throw new DomainError('OUTSIDE_OPERATING_HOURS','The selected time is outside operating hours.',409);const windowEnd=new Date();windowEnd.setUTCDate(windowEnd.getUTCDate()+settings.bookingWindowDays);if(new Date(startAt)<new Date()||new Date(startAt)>windowEnd)throw new DomainError('INVALID_TIME_RANGE','The selected date is outside the booking window.',400);return endAt}
export function calculateAuthoritativePrice(context:BookingContext,startAt:string,endAt:string){const segments:PriceSegment[]=[];let cursor=startAt;while(new Date(cursor)<new Date(endAt)){const date=localDate(cursor,context.turf.timezone);const minute=localMinute(cursor,context.turf.timezone);const day=weekday(date);const rule=context.pricingRules.filter(r=>r.days.includes(day)&&minute>=r.startTime&&minute<r.endTime).sort((a,b)=>b.priority-a.priority)[0];if(!rule)throw new DomainError('INVALID_TIME_RANGE','Pricing is not configured for this time.',409);const minutes=Math.min(context.settings.slotIntervalMinutes,(new Date(endAt).getTime()-new Date(cursor).getTime())/60000);segments.push({startAt:cursor,endAt:addMinutes(cursor,minutes),minutes,hourlyRate:rule.hourlyRate,amount:Math.round(rule.hourlyRate*minutes/60*100)/100,ruleId:rule.id});cursor=addMinutes(cursor,minutes)}return{total:Math.round(segments.reduce((s,x)=>s+x.amount,0)*100)/100,segments}}
export const payableNow=(settings:BookingContext['settings'],total:number)=>settings.paymentMode==='FULL'?total:settings.paymentMode==='PERCENTAGE'?Math.round(total*settings.advanceValue)/100:Math.min(total,settings.advanceValue)
export const phoneLookupHash=(normalized:string)=>{const secret=process.env.BOOKING_LOOKUP_HMAC_SECRET;if(!secret)throw new DomainError('CONFIGURATION_ERROR','Booking lookup is not configured.',500);return createHmac('sha256',secret).update(normalized).digest('hex')}
export function audit(tenantId:string,actorType:AuditEvent['actorType'],actorId:string,action:string,entityType:string,entityId:string,requestId:string,after?:Record<string,unknown>):AuditEvent{return{tenantId,actorType,actorId,action,entityType,entityId,requestId,after,createdAt:new Date().toISOString()}}

export async function createServerHold(repo:AuthoritativeRepository,context:BookingContext,input:{startAt:string;durationMinutes:number;customerSessionId:string;requestId:string}){const endAt=assertBookable(context,input.startAt,input.durationMinutes);const price=calculateAuthoritativePrice(context,input.startAt,endAt);const now=new Date().toISOString();const expired=await repo.listExpiredActiveHolds(context.tenant.id,context.turf.turfId,now,25);for(const old of expired)await repo.expireHoldAtomic(old.tenantId,old.id,now,audit(old.tenantId,'SYSTEM','lazy-hold-cleanup','HOLD_EXPIRED','HOLD',old.id,input.requestId));const amountNow=payableNow(context.settings,price.total);const holdId=`hold_${crypto.randomUUID()}`;const expiresAt=addMinutes(now,context.settings.holdDurationMinutes);const authoritativePricing={total:price.total,payableNow:amountNow,paymentAmountMode:context.settings.paymentMode,advanceValue:context.settings.advanceValue,currency:'INR' as const,segments:price.segments,capturedAt:now};const hold:ServerHold={id:holdId,tenantId:context.tenant.id,turfId:context.turf.turfId,customerSessionId:input.customerSessionId,startAt:input.startAt,endAt,expiresAt,status:'ACTIVE',paymentOrderIds:[],authoritativePricing,paymentCollectionMode:context.settings.paymentCollectionMode??'CASHFREE',createdAt:now,updatedAt:now};const locks=lockRange(context.tenant.id,context.turf.turfId,input.startAt,endAt,context.settings.slotIntervalMinutes,'HOLD',holdId,expiresAt);await repo.createHoldAtomic({hold,locks,audit:audit(context.tenant.id,'CUSTOMER',input.customerSessionId,'HOLD_CREATED','HOLD',holdId,input.requestId,{startAt:input.startAt,endAt,total:price.total,payableNow:amountNow})},now);return{hold,price,payableNow:amountNow}}

export function buildPaidBooking(context:BookingContext,hold:ServerHold,customer:{name:string;phone:string;email?:string},amountPaid:number,orderId:string,providerPaymentId?:string,paymentMethod='CASHFREE',verifiedBy:{type:'USER'|'SYSTEM';id:string}={type:'SYSTEM',id:'payment-provider'}):ServerBooking{const snapshot=hold.authoritativePricing;const now=new Date().toISOString();const id=`TM-${crypto.randomUUID().replace(/-/g,'').slice(0,12).toUpperCase()}`;return{id,tenantId:context.tenant.id,turfId:context.turf.turfId,customerName:customer.name,customerPhone:customer.phone,customerPhoneNormalized:customer.phone,customerPhoneLookupHash:phoneLookupHash(customer.phone),customerEmail:customer.email,startAt:hold.startAt,endAt:hold.endAt,durationMinutes:(new Date(hold.endAt).getTime()-new Date(hold.startAt).getTime())/60000,calculatedPrice:snapshot.total,finalPrice:snapshot.total,priceOverridden:false,pricingSnapshot:snapshot.segments,amountPaid,balanceDue:Math.max(0,snapshot.total-amountPaid),currency:snapshot.currency,bookingStatus:'CONFIRMED',paymentStatus:amountPaid>=snapshot.total?'PAID':'ADVANCE_PAID',paymentMethod,source:'ONLINE',holdId:hold.id,paymentOrderId:orderId,providerPaymentId,paymentVerifiedAt:now,paymentVerifiedBy:verifiedBy,createdBy:{type:'CUSTOMER',id:hold.customerSessionId},createdAt:now,updatedAt:now}}

export function buildManualUpiBooking(context:BookingContext,hold:ServerHold,order:PaymentOrder,actorId:string){return buildPaidBooking(context,hold,order.customer,order.expectedAmount,order.merchantOrderId,undefined,'MANUAL_UPI',{type:'USER',id:actorId})}

export async function createManualBooking(repo:AuthoritativeRepository,context:BookingContext,input:{startAt:string;durationMinutes:number;customerName:string;customerPhone:string;customerEmail?:string;finalPrice?:number;paymentStatus:ServerBooking['paymentStatus'];notes?:string;actorId:string;requestId:string}){
 const endAt=assertBookable(context,input.startAt,input.durationMinutes)
 const price=calculateAuthoritativePrice(context,input.startAt,endAt)
 const finalPrice=input.finalPrice??price.total
 const paid=['PAID','CASH','COMPLIMENTARY'].includes(input.paymentStatus)?finalPrice:0
 const now=new Date().toISOString()
 const booking:ServerBooking={id:`TM-${crypto.randomUUID().replace(/-/g,'').slice(0,12).toUpperCase()}`,tenantId:context.tenant.id,turfId:context.turf.turfId,customerName:input.customerName,customerPhone:input.customerPhone,customerPhoneNormalized:input.customerPhone,customerPhoneLookupHash:phoneLookupHash(input.customerPhone),customerEmail:input.customerEmail,startAt:input.startAt,endAt,durationMinutes:input.durationMinutes,calculatedPrice:price.total,finalPrice,priceOverridden:finalPrice!==price.total,pricingSnapshot:price.segments,amountPaid:paid,balanceDue:Math.max(0,finalPrice-paid),currency:'INR',bookingStatus:'CONFIRMED',paymentStatus:input.paymentStatus,paymentMethod:input.paymentStatus,source:'MANUAL',notes:input.notes,createdBy:{type:'USER',id:input.actorId},createdAt:now,updatedAt:now}
 const locks=lockRange(context.tenant.id,context.turf.turfId,input.startAt,endAt,context.settings.slotIntervalMinutes,'BOOKING',booking.id)
 await repo.createManualBookingAtomic(booking,locks,audit(context.tenant.id,'USER',input.actorId,'MANUAL_BOOKING_CREATED','BOOKING',booking.id,input.requestId,{startAt:booking.startAt,endAt:booking.endAt,finalPrice:booking.finalPrice}),now)
 return booking
}
