import 'server-only'
import { FieldValue } from 'firebase-admin/firestore'
import { adminDb } from '@/lib/firebase/admin'
import { DomainError } from '@/lib/domain/errors'
import { lockRange } from '@/lib/services/bookings/booking-engine'
import type { BookingContext,AuthoritativeRepository } from '@/lib/repositories/contracts'
export type BlockInput={turfId:string;startAt:string;endAt:string;reason:string;notes?:string}
export async function saveBlock(repo:AuthoritativeRepository,context:BookingContext,input:BlockInput,actorId:string,requestId:string,id=`BL-${crypto.randomUUID()}`){if(new Date(input.startAt)>=new Date(input.endAt)||new Date(input.startAt)<new Date())throw new DomainError('INVALID_TIME_RANGE','Choose a valid future time range.',400);if(input.turfId!==context.turf.turfId)throw new DomainError('FORBIDDEN','Turf does not belong to this workspace.',403);const db=adminDb();const locks=lockRange(context.tenant.id,input.turfId,input.startAt,input.endAt,context.settings.slotIntervalMinutes,'BLOCK',id);await db.runTransaction(async tx=>{const ref=db.doc(`tenants/${context.tenant.id}/blocks/${id}`);const oldLocks=await tx.get(db.collection(`tenants/${context.tenant.id}/slotLocks`).where('resourceId','==',id));const refs=locks.map(lock=>db.doc(`tenants/${context.tenant.id}/slotLocks/${lock.id}`));const snaps=await Promise.all(refs.map(lock=>tx.get(lock)));snaps.forEach(snap=>{if(snap.exists&&snap.data()?.resourceId!==id)throw new DomainError('SLOT_CONFLICT','That time is no longer available.',409)});oldLocks.docs.forEach(lock=>tx.delete(lock.ref));refs.forEach((lock,index)=>tx.set(lock,{...locks[index],createdAt:FieldValue.serverTimestamp()}));tx.set(ref,{id,tenantId:context.tenant.id,...input,createdBy:actorId,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});tx.create(db.collection(`tenants/${context.tenant.id}/auditLogs`).doc(),{tenantId:context.tenant.id,actorType:'USER',actorId,action:'BLOCK_SAVED',entityType:'BLOCK',entityId:id,requestId,createdAt:FieldValue.serverTimestamp()})});return{id,...input}}
export async function deleteBlock(tenantId:string,id:string,actorId:string,requestId:string){const db=adminDb();await db.runTransaction(async tx=>{const ref=db.doc(`tenants/${tenantId}/blocks/${id}`);const [block,locks]=await Promise.all([tx.get(ref),tx.get(db.collection(`tenants/${tenantId}/slotLocks`).where('resourceId','==',id))]);if(!block.exists)throw new DomainError('BOOKING_NOT_FOUND','Blocked time was not found.',404);locks.docs.forEach(lock=>tx.delete(lock.ref));tx.delete(ref);tx.create(db.collection(`tenants/${tenantId}/auditLogs`).doc(),{tenantId,actorType:'USER',actorId,action:'BLOCK_REMOVED',entityType:'BLOCK',entityId:id,requestId,createdAt:FieldValue.serverTimestamp()})})}
