import { DomainError } from '../../domain/errors'
import type { AuditEvent,PaymentOrder,PublicTurf,RefundRecord,ServerBooking,SlotLock } from '../../domain/backend-types'
import type { AuthoritativeRepository,BookingContext,HoldWrite } from '../contracts'

export class MemoryRepository implements AuthoritativeRepository{
 publicTurfs=new Map<string,PublicTurf>();contexts=new Map<string,BookingContext>();locks=new Map<string,SlotLock>();holds=new Map<string,HoldWrite['hold']>();orders=new Map<string,PaymentOrder>();bookings=new Map<string,ServerBooking>();refunds=new Map<string,RefundRecord>();webhookEvents=new Set<string>();audits:AuditEvent[]=[]
 seed(context:BookingContext){this.publicTurfs.set(context.turf.slug,context.turf);this.contexts.set(`${context.tenant.id}:${context.turf.turfId}`,context)}
 async resolvePublicTurf(slug:string){return this.publicTurfs.get(slug)??null}
 async getBookingContext(tenantId:string,turfId:string){return this.contexts.get(`${tenantId}:${turfId}`)??null}
 async createHoldAtomic(input:HoldWrite,now:string){for(const lock of input.locks){const old=this.locks.get(lock.id);if(old&&!(old.lockType==='HOLD'&&old.reconciled&&old.expiresAt&&old.expiresAt<=now))throw new DomainError('SLOT_CONFLICT','That time is no longer available.',409)}this.holds.set(input.hold.id,input.hold);input.locks.forEach(l=>this.locks.set(l.id,l));this.audits.push(input.audit)}
 async listExpiredActiveHolds(tenantId:string,turfId:string,now:string,limit=25){return[...this.holds.values()].filter(h=>h.tenantId===tenantId&&h.turfId===turfId&&h.status==='ACTIVE'&&h.expiresAt<=now).slice(0,limit)}
 async listExpiredActiveHoldsGlobal(now:string,limit=100){return[...this.holds.values()].filter(h=>h.status==='ACTIVE'&&h.expiresAt<=now).slice(0,limit)}
 async hasPendingManualClaim(tenantId:string,customerSessionId:string){return[...this.holds.values()].some(h=>h.tenantId===tenantId&&h.customerSessionId===customerSessionId&&h.status==='PAYMENT_PENDING')}
 async expireHoldAtomic(tenantId:string,holdId:string,now:string,audit:AuditEvent){const hold=this.holds.get(holdId);if(!hold||hold.tenantId!==tenantId||hold.status!=='ACTIVE'||hold.expiresAt>now)return'SKIPPED' as const;this.holds.set(holdId,{...hold,status:'EXPIRED'});for(const[key,lock]of this.locks)if(lock.resourceId===holdId&&lock.lockType==='HOLD')this.locks.delete(key);for(const orderId of hold.paymentOrderIds??[]){const order=this.orders.get(orderId);if(order&&['CREATED','ACTIVE','FAILED'].includes(order.status))this.orders.set(orderId,{...order,status:'EXPIRED'})}this.audits.push(audit);return'EXPIRED' as const}
 async createManualBookingAtomic(booking:ServerBooking,locks:SlotLock[],audit:AuditEvent){if(locks.some(l=>this.locks.has(l.id)))throw new DomainError('SLOT_CONFLICT','That time is no longer available.',409);this.bookings.set(booking.id,booking);locks.forEach(l=>this.locks.set(l.id,l));this.audits.push(audit)}
 async savePaymentOrder(order:PaymentOrder){if(this.orders.has(order.merchantOrderId))throw new DomainError('SLOT_CONFLICT','Payment order exists.',409);this.orders.set(order.merchantOrderId,order);const hold=this.holds.get(order.holdId);if(hold)this.holds.set(hold.id,{...hold,paymentOrderIds:[...new Set([...hold.paymentOrderIds,order.merchantOrderId])],paymentReference:order.paymentReference??order.merchantOrderId})}
 async getPaymentOrder(id:string){return this.orders.get(id)??null}
 async getHold(_tenantId:string,id:string){return this.holds.get(id)??null}
 async updatePaymentOrder(id:string,changes:Partial<PaymentOrder>){const old=this.orders.get(id);if(!old)throw new DomainError('PAYMENT_FAILED','Order not found.',404);this.orders.set(id,{...old,...changes})}
 async markPaymentAttention(id:string,reason:string,audit:AuditEvent){const old=this.orders.get(id);if(!old)throw new DomainError('PAYMENT_FAILED','Order not found.',404);this.orders.set(id,{...old,status:'REQUIRES_ATTENTION',rejectionReason:reason});this.audits.push(audit)}
 async claimManualPayment(orderId:string,customerSessionId:string,now:string,audit:AuditEvent){const order=this.orders.get(orderId),hold=order&&this.holds.get(order.holdId);if(!order||!hold)throw new DomainError('HOLD_EXPIRED','The payment time has expired.',409);if(order.status==='PAYMENT_PENDING'&&hold.status==='PAYMENT_PENDING')return order;if(order.paymentCollectionMode!=='MANUAL_UPI'||hold.customerSessionId!==customerSessionId||hold.status!=='ACTIVE'||hold.expiresAt<now||![...this.locks.values()].some(l=>l.resourceId===hold.id&&l.lockType==='HOLD'))throw new DomainError('HOLD_EXPIRED','The payment time has expired.',409);const next={...order,status:'PAYMENT_PENDING' as const,paymentClaimedAt:now};this.orders.set(orderId,next);this.holds.set(hold.id,{...hold,status:'PAYMENT_PENDING',paymentClaimedAt:now});this.audits.push(audit);return next}
 async approveManualPayment(orderId:string,tenantId:string,booking:ServerBooking,actorId:string,now:string,audit:AuditEvent){const order=this.orders.get(orderId);if(!order||order.tenantId!==tenantId)throw new DomainError('BOOKING_NOT_FOUND','Payment claim was not found.',404);if(order.bookingId)return this.bookings.get(order.bookingId)!;const hold=this.holds.get(order.holdId);if(!hold||hold.status!=='PAYMENT_PENDING')throw new DomainError('HOLD_EXPIRED','The payment claim is no longer awaiting review.',409);this.bookings.set(booking.id,booking);this.orders.set(orderId,{...order,status:'PAID',bookingId:booking.id,paidAt:now,reviewedAt:now,reviewedBy:actorId});this.holds.set(hold.id,{...hold,status:'CONVERTED',bookingId:booking.id,reviewedAt:now,reviewedBy:actorId});for(const[id,lock]of this.locks)if(lock.resourceId===hold.id&&lock.lockType==='HOLD')this.locks.set(id,{...lock,lockType:'BOOKING',resourceId:booking.id,expiresAt:undefined});this.audits.push(audit);return booking}
 async rejectManualPayment(orderId:string,tenantId:string,actorId:string,reason:string,now:string,audit:AuditEvent){const order=this.orders.get(orderId);if(!order||order.tenantId!==tenantId)throw new DomainError('BOOKING_NOT_FOUND','Payment claim was not found.',404);if(order.status==='REJECTED')return order;if(order.status!=='PAYMENT_PENDING')throw new DomainError('PAYMENT_FAILED','Payment claim is not awaiting review.',409);const hold=this.holds.get(order.holdId);if(!hold||hold.status!=='PAYMENT_PENDING')throw new DomainError('HOLD_EXPIRED','The payment claim is no longer awaiting review.',409);const next={...order,status:'REJECTED' as const,rejectionReason:reason,reviewedAt:now,reviewedBy:actorId};this.orders.set(orderId,next);this.holds.set(hold.id,{...hold,status:'RELEASED',rejectionReason:reason,reviewedAt:now,reviewedBy:actorId});for(const[key,lock]of this.locks)if(lock.resourceId===hold.id&&lock.lockType==='HOLD')this.locks.delete(key);this.audits.push(audit);return next}
 async finalizePaidBooking(orderId:string,booking:ServerBooking,audit:AuditEvent){const order=this.orders.get(orderId);if(!order)throw new DomainError('PAYMENT_FAILED','Order not found.',404);if(order.bookingId)return this.bookings.get(order.bookingId)!;if(order.status!=='PAID')throw new DomainError('PAYMENT_PENDING','Payment is not verified.',409);const hold=this.holds.get(order.holdId);if(!hold||hold.status!=='ACTIVE'||hold.expiresAt<=new Date().toISOString()||![...this.locks.values()].some(l=>l.resourceId===hold.id&&l.lockType==='HOLD'))throw new DomainError('HOLD_EXPIRED','The paid reservation requires manual reconciliation.',409);this.bookings.set(booking.id,booking);this.orders.set(orderId,{...order,bookingId:booking.id});this.holds.set(hold.id,{...hold,status:'CONVERTED',bookingId:booking.id});for(const [id,lock] of this.locks)if(lock.resourceId===order.holdId)this.locks.set(id,{...lock,lockType:'BOOKING',resourceId:booking.id,expiresAt:undefined});this.audits.push(audit);return booking}
 async getBookingByLocator(id:string){return this.bookings.get(id)??null}
 async cancelBookingAtomic(id:string,tenantId:string,actor:{type:'CUSTOMER'|'USER';id:string},reason:string,refund?:RefundRecord){const booking=this.bookings.get(id);if(!booking||booking.tenantId!==tenantId)throw new DomainError('BOOKING_NOT_FOUND','Booking not found.',404);if(booking.bookingStatus==='CANCELLED')return{booking,refund:refund?this.refunds.get(refund.refundId):undefined,alreadyCancelled:true};if(booking.bookingStatus==='COMPLETED')throw new DomainError('BOOKING_ALREADY_COMPLETED','Completed bookings cannot be cancelled.',409);const next={...booking,bookingStatus:'CANCELLED' as const,paymentStatus:refund?'REFUND_PENDING' as const:booking.paymentStatus,manualRefundRequired:booking.paymentMethod==='MANUAL_UPI'&&booking.amountPaid>0,cancellation:{reason,actor,cancelledAt:new Date().toISOString()}};this.bookings.set(id,next);for(const [key,lock] of this.locks)if(lock.resourceId===id)this.locks.delete(key);if(refund&&!this.refunds.has(refund.refundId))this.refunds.set(refund.refundId,refund);return{booking:next,refund:refund?this.refunds.get(refund.refundId):undefined,alreadyCancelled:false}}
 async getRefund(id:string){return this.refunds.get(id)??null}
 async updateRefund(id:string,changes:Partial<RefundRecord>){const old=this.refunds.get(id);if(!old)throw new DomainError('PAYMENT_FAILED','Refund not found.',404);this.refunds.set(id,{...old,...changes});const booking=this.bookings.get(old.bookingId);if(booking&&changes.status)this.bookings.set(old.bookingId,{...booking,paymentStatus:changes.status==='SUCCESS'?'REFUNDED':changes.status==='FAILED'||changes.status==='CANCELLED'?'REFUND_FAILED':'REFUND_PENDING'})}
 async claimWebhookEvent(id:string){if(this.webhookEvents.has(id))return false;this.webhookEvents.add(id);return true}
 async releaseWebhookEvent(id:string){this.webhookEvents.delete(id)}
}
