export type Role = 'OWNER'|'MANAGER'|'STAFF'
export type Permission = 'tenant:manage'|'bookings:read'|'bookings:write'|'bookings:cancel'|'payments:manage'|'blocks:manage'|'pricing:manage'|'reports:read'
export type MembershipStatus = 'ACTIVE'|'SUSPENDED'
export type ServerBookingStatus = 'CONFIRMED'|'COMPLETED'|'CANCELLATION_REQUESTED'|'CANCELLED'
export type ServerPaymentStatus = 'UNPAID'|'PENDING'|'ADVANCE_PAID'|'PAID'|'PAY_AT_VENUE'|'CASH'|'COMPLIMENTARY'|'REFUND_PENDING'|'PARTIALLY_REFUNDED'|'REFUNDED'|'REFUND_FAILED'
export type HoldStatus = 'ACTIVE'|'PAYMENT_PENDING'|'CONVERTED'|'EXPIRED'|'RELEASED'
export type LockType = 'HOLD'|'BOOKING'|'BLOCK'
export type PaymentCollectionMode = 'MANUAL_UPI'|'CASHFREE'

export interface TenantRecord { id:string; slug:string; legalName:string; displayName:string; status:'ACTIVE'|'SUSPENDED'; timezone:string; createdAt:string; updatedAt:string }
export interface TenantMember { uid:string; tenantId:string; role:Role; permissions:Permission[]; status:MembershipStatus; createdAt:string; updatedAt:string }
export interface PublicTurf { tenantId:string; turfId:string; slug:string; name:string; shortName:string; address:string; locality:string; mapUrl:string; phone:string; whatsapp:string; sports:string[]; amenities:string[]; timezone:string; branding:Record<string,string>; isBookingEnabled:boolean }
export interface ServerPricingRule { id:string; tenantId:string; turfId:string; days:number[]; startTime:number; endTime:number; hourlyRate:number; currency:'INR'; priority:number; activeFrom?:string; activeUntil?:string }
export interface ManualUpiSettings { upiId:string;payeeName?:string;instructions?:string }
export interface ServerBookingSettings { paymentMode:'FULL'|'FIXED'|'PERCENTAGE'; paymentCollectionMode?:PaymentCollectionMode; manualUpi?:ManualUpiSettings; advanceValue:number; minDurationMinutes:number; maxDurationMinutes:number; slotIntervalMinutes:30|60; cancellationEnabled:boolean; cancellationCutoffHours:number; bookingWindowDays:number; holdDurationMinutes:number }
export interface ServerOperatingDay { weekday:number; closed:boolean; openMinute:number; closeMinute:number }
export interface PriceSegment { startAt:string; endAt:string; minutes:number; hourlyRate:number; amount:number; ruleId:string }
export interface AuthoritativePricingSnapshot { total:number;payableNow:number;paymentAmountMode:'FULL'|'FIXED'|'PERCENTAGE';advanceValue:number;currency:'INR';segments:PriceSegment[];capturedAt:string }
export interface ServerBooking { id:string; tenantId:string; turfId:string; customerName:string; customerPhone:string; customerPhoneNormalized:string; customerPhoneLookupHash:string; customerEmail?:string; startAt:string; endAt:string; durationMinutes:number; calculatedPrice:number; finalPrice:number; priceOverridden:boolean; pricingSnapshot:PriceSegment[]; amountPaid:number; balanceDue:number; currency:'INR'; bookingStatus:ServerBookingStatus; paymentStatus:ServerPaymentStatus; paymentMethod:string; source:'ONLINE'|'MANUAL'; notes?:string; holdId?:string; paymentOrderId?:string; providerPaymentId?:string; paymentVerifiedAt?:string;paymentVerifiedBy?:{type:'USER'|'SYSTEM';id:string};manualRefundRequired?:boolean; createdBy:{type:'CUSTOMER'|'USER'|'SYSTEM';id:string}; createdAt:string; updatedAt:string }
export interface ServerHold { id:string; tenantId:string; turfId:string; customerSessionId:string; startAt:string; endAt:string; expiresAt:string; status:HoldStatus; paymentOrderIds:string[]; authoritativePricing:AuthoritativePricingSnapshot;paymentCollectionMode?:PaymentCollectionMode;paymentReference?:string;paymentClaimedAt?:string;reviewedAt?:string;reviewedBy?:string;rejectionReason?:string;bookingId?:string; createdAt:string; updatedAt:string }
export interface SlotLock { id:string; tenantId:string; turfId:string; slotStartAt:string; slotEndAt:string; lockType:LockType; resourceId:string; expiresAt?:string; reconciled?:boolean; createdAt:string }
export interface PaymentOrder { merchantOrderId:string; tenantId:string; turfId:string; holdId:string; bookingId?:string; provider:'CASHFREE'|'MOCK'|'MANUAL_UPI'; paymentCollectionMode?:PaymentCollectionMode;providerOrderId?:string; providerPaymentId?:string; startAt:string;endAt:string;durationMinutes:number;expectedAmount:number; currency:'INR'; authoritativePricing:AuthoritativePricingSnapshot;status:'CREATED'|'ACTIVE'|'PAYMENT_PENDING'|'PAID'|'FAILED'|'EXPIRED'|'REJECTED'|'REQUIRES_ATTENTION'; idempotencyKey:string; requestHash:string; customerAccessTokenHash:string; customer:{name:string;phone:string;email?:string}; expiresAt:string; paymentSessionId?:string; paymentReference?:string;upiId?:string;payeeName?:string;paymentInstructions?:string;paymentClaimedAt?:string;reviewedAt?:string;reviewedBy?:string;rejectionReason?:string;createdAt:string; updatedAt:string; paidAt?:string }
export interface RefundRecord { refundId:string;tenantId:string;turfId:string;bookingId:string;paymentOrderId:string;providerOrderId:string;providerPaymentId?:string;providerRefundId?:string;requestedAmount:number;confirmedAmount:number;currency:'INR';reason:string;status:'REQUESTED'|'PENDING'|'SUCCESS'|'FAILED'|'CANCELLED';idempotencyKey:string;requestedBy:{type:'CUSTOMER'|'USER';id:string};createdAt:string;updatedAt:string;processedAt?:string;failureReason?:string }
export interface AuditEvent { tenantId:string; actorType:'CUSTOMER'|'USER'|'SYSTEM'; actorId:string; action:string; entityType:string; entityId:string; requestId:string; before?:Record<string,unknown>; after?:Record<string,unknown>; createdAt:string }
