export type ErrorCode = 'UNAUTHENTICATED'|'FORBIDDEN'|'INVALID_APP_CHECK'|'TENANT_NOT_FOUND'|'TENANT_SUSPENDED'|'TURF_NOT_FOUND'|'BOOKING_DISABLED'|'INVALID_TIME_RANGE'|'OUTSIDE_OPERATING_HOURS'|'SLOT_CONFLICT'|'HOLD_EXPIRED'|'PAYMENT_PENDING'|'PAYMENT_FAILED'|'PAYMENT_MISMATCH'|'BOOKING_NOT_FOUND'|'CANCELLATION_NOT_ALLOWED'|'CANCELLATION_CUTOFF_PASSED'|'BOOKING_ALREADY_CANCELLED'|'BOOKING_ALREADY_COMPLETED'|'REFUND_REQUIRED'|'RATE_LIMITED'|'CONFIGURATION_ERROR'|'VALIDATION_ERROR'|'INTERNAL_ERROR'
export class DomainError extends Error {
  constructor(public readonly code: ErrorCode, message: string, public readonly status = 400, public readonly retryAfterSeconds?:number) { super(message); this.name = 'DomainError' }
}
