import 'server-only'
import { createHmac,timingSafeEqual } from 'node:crypto'
import { DomainError } from '@/lib/domain/errors'
import type { CreateOrderInput,PaymentProvider,ProviderOrder,ProviderRefund,RefundInput } from './provider'

type CashfreeOrder={cf_order_id:string;order_id:string;order_status:string;order_amount:number;order_currency:string;payment_session_id:string;order_expiry_time:string}
type CashfreePayment={cf_payment_id:string;payment_status:string;payment_amount:number;payment_currency:string}
export class CashfreePaymentProvider implements PaymentProvider{
 private get baseUrl(){return process.env.CASHFREE_ENV==='production'?'https://api.cashfree.com/pg':'https://sandbox.cashfree.com/pg'}
 private headers(idempotencyKey?:string,requestId?:string){const id=process.env.CASHFREE_CLIENT_ID;const secret=process.env.CASHFREE_CLIENT_SECRET;if(!id||!secret)throw new DomainError('CONFIGURATION_ERROR','Cashfree credentials are not configured.',503);return{'content-type':'application/json','x-client-id':id,'x-client-secret':secret,'x-api-version':process.env.CASHFREE_API_VERSION??'2026-01-01',...(idempotencyKey?{'x-idempotency-key':idempotencyKey}:{}),...(requestId?{'x-request-id':requestId}:{})}}
 private async call<T>(path:string,init:RequestInit,idempotencyKey?:string,requestId?:string){const response=await fetch(`${this.baseUrl}${path}`,{...init,headers:{...this.headers(idempotencyKey,requestId),...init.headers},cache:'no-store'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new DomainError('PAYMENT_FAILED',response.status>=500?'Payment provider is temporarily unavailable.':'Payment request was rejected.',response.status>=500?503:400);return body as T}
 async createOrder(input:CreateOrderInput){const body={order_id:input.merchantOrderId,order_amount:input.amount,order_currency:input.currency,customer_details:{customer_id:input.customer.id,customer_name:input.customer.name,customer_phone:input.customer.phone.slice(-10),...(input.customer.email?{customer_email:input.customer.email}:{})},order_meta:{return_url:input.returnUrl,notify_url:input.notifyUrl},order_expiry_time:input.expiresAt,order_note:'TurfMate booking payment'};const o=await this.call<CashfreeOrder>('/orders',{method:'POST',body:JSON.stringify(body)},input.idempotencyKey,input.requestId);return{providerOrderId:o.cf_order_id,paymentSessionId:o.payment_session_id,status:mapOrderStatus(o.order_status),amount:o.order_amount,currency:o.order_currency,expiresAt:o.order_expiry_time} as ProviderOrder}
 async getOrder(orderId:string){const o=await this.call<CashfreeOrder>(`/orders/${encodeURIComponent(orderId)}`,{method:'GET'});return{providerOrderId:o.cf_order_id,paymentSessionId:o.payment_session_id,status:mapOrderStatus(o.order_status),amount:o.order_amount,currency:o.order_currency,expiresAt:o.order_expiry_time}}
 async getPaymentsForOrder(orderId:string){const payments=await this.call<CashfreePayment[]>(`/orders/${encodeURIComponent(orderId)}/payments`,{method:'GET'});return payments.map(payment=>({id:payment.cf_payment_id,status:payment.payment_status,amount:payment.payment_amount,currency:payment.payment_currency}))}
 verifyWebhook(rawBody:string,timestamp:string,signature:string){const secret=process.env.CASHFREE_CLIENT_SECRET;if(!secret||!timestamp||!signature)return false;const age=Math.abs(Date.now()-Number(timestamp));if(!Number.isFinite(age)||age>300_000)return false;const expected=createHmac('sha256',secret).update(timestamp+rawBody).digest();let actual:Buffer;try{actual=Buffer.from(signature,'base64')}catch{return false}return actual.length===expected.length&&timingSafeEqual(actual,expected)}
 async createRefund(input:RefundInput){const r=await this.call<{cf_refund_id:string;refund_status:string;refund_amount:number}>(`/orders/${encodeURIComponent(input.providerOrderId)}/refunds`,{method:'POST',body:JSON.stringify({refund_id:input.refundId,refund_amount:input.amount,refund_note:input.note})},input.idempotencyKey);return{providerRefundId:r.cf_refund_id,status:mapRefund(r.refund_status),amount:r.refund_amount}}
 async getRefund(orderId:string,refundId:string){const r=await this.call<{cf_refund_id:string;refund_status:string;refund_amount:number}>(`/orders/${encodeURIComponent(orderId)}/refunds/${encodeURIComponent(refundId)}`,{method:'GET'});return{providerRefundId:r.cf_refund_id,status:mapRefund(r.refund_status),amount:r.refund_amount}}
}
const mapOrderStatus=(s:string):ProviderOrder['status']=>s==='PAID'?'PAID':s==='EXPIRED'?'EXPIRED':s==='ACTIVE'?'ACTIVE':'FAILED'
const mapRefund=(s:string):ProviderRefund['status']=>s==='SUCCESS'?'SUCCESS':s==='FAILED'?'FAILED':s==='CANCELLED'?'CANCELLED':'PENDING'
