import { readFileSync } from 'node:fs'
import { assertFails,assertSucceeds,initializeTestEnvironment,type RulesTestEnvironment } from '@firebase/rules-unit-testing'
import { afterAll,beforeAll,beforeEach,describe,it } from 'vitest'
import { doc,getDoc,setDoc } from 'firebase/firestore'

const run=Boolean(process.env.FIRESTORE_EMULATOR_HOST)
describe.skipIf(!run)('Firestore tenant isolation rules',()=>{
 let env:RulesTestEnvironment
 beforeAll(async()=>{env=await initializeTestEnvironment({projectId:'turfmate-rules-test',firestore:{rules:readFileSync('firestore.rules','utf8')}})})
 afterAll(async()=>env.cleanup())
 beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async context=>{const db=context.firestore();const publicData={tenantId:'tenant-a',turfId:'turf-a',slug:'arena-a',name:'Arena A',shortName:'Arena',address:'Address',locality:'Mumbai',mapUrl:'',phone:'9999999999',whatsapp:'9999999999',sports:['Football'],amenities:[],timezone:'Asia/Kolkata',branding:{primary:'#111'},isBookingEnabled:true};await setDoc(doc(db,'publicTurfs/arena-a'),publicData);await setDoc(doc(db,'tenants/tenant-a'),{displayName:'A'});await setDoc(doc(db,'tenants/tenant-b'),{displayName:'B'});await setDoc(doc(db,'tenants/tenant-a/members/owner-a'),{status:'ACTIVE',role:'OWNER'});await setDoc(doc(db,'tenants/tenant-a/members/staff-a'),{status:'ACTIVE',role:'STAFF'});await setDoc(doc(db,'tenants/tenant-a/members/suspended-a'),{status:'SUSPENDED',role:'OWNER'});await setDoc(doc(db,'tenants/tenant-b/members/owner-b'),{status:'ACTIVE',role:'OWNER'});await setDoc(doc(db,'tenants/tenant-a/bookings/a1'),{startAt:'2099-01-01T10:00:00Z'});await setDoc(doc(db,'tenants/tenant-b/bookings/b1'),{startAt:'2099-01-01T10:00:00Z'});await setDoc(doc(db,'tenants/tenant-a/paymentAttempts/p1'),{status:'PAYMENT_PENDING'});await setDoc(doc(db,'tenants/tenant-b/paymentAttempts/p2'),{status:'PAYMENT_PENDING'});await setDoc(doc(db,'paymentOrders/order-1'),{status:'PAID'});await setDoc(doc(db,'bookingLocators/a1'),{tenantId:'tenant-a'});await setDoc(doc(db,'webhookEvents/e1'),{type:'payment'})})})
 it('allows anonymous safe public reads only',async()=>{const db=env.unauthenticatedContext().firestore();await assertSucceeds(getDoc(doc(db,'publicTurfs/arena-a')));await assertFails(getDoc(doc(db,'tenants/tenant-a/bookings/a1')))})
 it('allows active members only inside their tenant',async()=>{const a=env.authenticatedContext('owner-a').firestore();await assertSucceeds(getDoc(doc(a,'tenants/tenant-a/bookings/a1')));await assertSucceeds(getDoc(doc(a,'tenants/tenant-a/paymentAttempts/p1')));await assertFails(getDoc(doc(a,'tenants/tenant-b/bookings/b1')));await assertFails(getDoc(doc(a,'tenants/tenant-b/paymentAttempts/p2')));const suspended=env.authenticatedContext('suspended-a').firestore();await assertFails(getDoc(doc(suspended,'tenants/tenant-a/bookings/a1')))})
 it('denies all client authoritative writes, including staff',async()=>{const owner=env.authenticatedContext('owner-a').firestore();const staff=env.authenticatedContext('staff-a').firestore();await assertFails(setDoc(doc(owner,'tenants/tenant-a/bookings/new'),{status:'CONFIRMED'}));await assertFails(setDoc(doc(staff,'tenants/tenant-a/settings/booking'),{holdDurationMinutes:1}))})
 it('keeps global server collections inaccessible',async()=>{const owner=env.authenticatedContext('owner-a').firestore();for(const path of ['paymentOrders/order-1','bookingLocators/a1','webhookEvents/e1'])await assertFails(getDoc(doc(owner,path)))})
})
