import 'server-only'
import { cookies } from 'next/headers'
import { adminAuth,adminDb } from '@/lib/firebase/admin'
import { DomainError } from '@/lib/domain/errors'
import { hasPermission } from './permissions'
import type { Permission,Role,TenantMember } from '@/lib/domain/backend-types'

export const sessionCookieName=()=>process.env.SESSION_COOKIE_NAME??'turfmate_session'
export async function createOwnerSession(idToken:string){const decoded=await adminAuth().verifyIdToken(idToken,true);if(!decoded.email_verified)throw new DomainError('FORBIDDEN','Verify your email before signing in.',403);const user=await adminDb().doc(`users/${decoded.uid}`).get();const tenantIds=(user.data()?.tenantIds??[]) as string[];for(const tenantId of tenantIds){const member=await adminDb().doc(`tenants/${tenantId}/members/${decoded.uid}`).get();if(member.exists&&member.data()?.status==='ACTIVE'){const maxAge=Number(process.env.SESSION_COOKIE_MAX_AGE??432000);return{cookie:await adminAuth().createSessionCookie(idToken,{expiresIn:maxAge*1000}),maxAge,uid:decoded.uid,tenantId}}}throw new DomainError('FORBIDDEN','No active TurfMate workspace membership was found.',403)}
export async function requireOwner(permission?:Permission){const value=(await cookies()).get(sessionCookieName())?.value;if(!value)throw new DomainError('UNAUTHENTICATED','Sign in to continue.',401);let decoded;try{decoded=await adminAuth().verifySessionCookie(value,true)}catch{throw new DomainError('UNAUTHENTICATED','Your session has expired. Sign in again.',401)}const user=await adminDb().doc(`users/${decoded.uid}`).get();const activeTenantId=(await cookies()).get('turfmate_active_tenant')?.value;const tenantIds=(user.data()?.tenantIds??[]) as string[];const tenantId=activeTenantId&&tenantIds.includes(activeTenantId)?activeTenantId:tenantIds[0];if(!tenantId)throw new DomainError('FORBIDDEN','No workspace membership was found.',403);const snap=await adminDb().doc(`tenants/${tenantId}/members/${decoded.uid}`).get();if(!snap.exists||snap.data()?.status!=='ACTIVE')throw new DomainError('TENANT_SUSPENDED','Workspace access is suspended.',403);const member={...snap.data(),uid:decoded.uid,tenantId} as TenantMember;if(permission&&!hasPermission(member.role as Role,permission,member.permissions))throw new DomainError('FORBIDDEN','You do not have permission for this action.',403);return{uid:decoded.uid,tenantId,member}}
